<?php
/**
 * Created by PhpStorm.
 * User: nhocconsanhdieu
 * Date: 13/5/2016
 * Time: 11:15 AM
 */
?>
<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
    /** ERROR */
    'ERROR_SYSTEM' => 'The system can not perform this feature, please comeback later',
    'ERROR_PARAM_NOT_VALIDATE' => 'Param is incorrect',
    'ERROR_ACCEPT_DENNY' => 'You are not allowed perform this feature!',
    'ERROR_can not_CHANGE_SUPPER_ADMIN' => 'You can not change SUPERADMIN acount information',
    'ERROR_can not_DELETE_YOURSELF' => 'You can not delete yourself',
    'ERROR_can not_BLOCK_YOURSELF' => 'You can not block yourself',
    'ERROR_can not_FIND_USER' => 'Account is not exist, please try again',
    'ERROR_can not_FIND_CATEGORY' => 'Category is not exist, please try again',
    'ERROR_can not_FIND_ADS' => 'Banner is not exist, please try again',
    'ERROR_can not_FIND_CONTENT_PACKAGE' => 'Game package is not exist, please try again',

    /** MSG */
    'MSG_BEUSER_CHANGE_PASSWORD_SUCCESS' => 'Changed password!!',
    'MSG_BEUSER_CHANGE_PASSWORD_FALSE' => 'Changed password unsuccessfully, please try again later!',
    'MSG_BEUSER_CHANGE_PASSWORD_NOT_VALIDATE' => 'Information is not valid, old password is incorrect',
    'MSG_BEUSER_CREATE_SUCCESS' => 'Created user!',
    'MSG_BEUSER_CREATE_FALSE' => 'Created user unsuccessfully, please try again later.',
    'MSG_BEUSER_UPDATE_SUCCESS' => 'Updated user!',
    'MSG_BEUSER_UPDATE_FALSE' => 'Updated user unsuccessfully, please try again later.',
    'MSG_BEUSER_DELETE_SUCCESS' => 'Deleted user!',
    'MSG_BEUSER_RESET_PASSWORD_SUCCESS' => 'Reseted password! New password is :',
    'MSG_BEUSER_ACTIVE_SUCCESS' => 'Activated user!',
    'MSG_BEUSER_INACTIVE_SUCCESS' => 'Inactivated user!',

    'MSG_USER_WHITELIST_NOT_ENTER_USER' => 'Information is not valid, subscriber can not empty - please enter again',
    'MSG_USER_ADD_TO_WHITELIST_SUCCESS' => 'Added the account to whitelist!',
    'MSG_USER_REMOVE_TO_WHITELIST_SUCCESS' => 'Removed account to whitelist!',
    'MSG_USER_NOT_SELECT_USER' => 'No account selected, please select account to continue',
    'MSG_USER_ALREADY_IN_WHITELIST' => 'The account already existed in whitelist.',
    'MSG_USER_ALREADY_IN_BLACKLIST' => 'The account already existed in blacklist.',
    'MSG_USER_ADD_TO_BLACKLIST_SUCCESS' => 'Added account to blacklist!',
    'MSG_USER_ADD_MULTI_TO_BLACKLIST_SUCCESS' => 'Added {count} accounts to blacklist!',
    'MSG_USER_BLACKLIST_NOT_INCLUDE_FILE' => 'Information is not valid, Account list does not update -  please enter again.',
    'MSG_USER_CANCEL_PACKAGE_USER_INACTIVE' => 'Cancel game package unsuccessfully, account is inactive, please try again later.',
//    'MSG_USER_CANCEL_PACKAGE_USER_INACTIVE' => 'Cancel game package unsuccessfully, account is inactive, please try again later',
    'MSG_USER_CANCEL_PACKAGE_SUCCESS' => 'Canceled game package!',
    'MSG_USER_REGISTER_PACKAGE_USER_INACTIVE' => 'Register Game package unsuccessfully, account is inactive, please try again later.',
    'MSG_USER_REGISTER_PACKAGE_PACKAGE_NOT_EXIST' => 'Register Game package unsuccessfully, the package does not exist, please try again later.',
    'MSG_USER_REGISTER_PACKAGE_SUCCESS' => 'Registered Game package!',

    'MSG_CATEGORY_CREATE_SUCCESS' => 'Created category!',
    'MSG_CATEGORY_UPDATE_SUCCESS' => 'Updated category!',
    'MSG_CATEGORY_DELETE_SUCCESS' => 'Deleted category!',
    'MSG_CATEGORY_DELETE_MULTI_SUCCESS' => 'Deleted {count} categories!',
    'MSG_CATEGORY_NOT_SELECT_CATEGORY' => 'No category selected, please select category to continue',
    'MSG_CATEGORY_ACTIVE_SUCCESS' => 'Activated category!',
    'MSG_CATEGORY_INACTIVE_SUCCESS' => 'Inactivated category!',
    'MSG_CONTENT_DELETE_SUCCESS' => 'Deleted category!',

    'MSG_CONTENT_RECOMMENDATION_DELETE_SUCCESS' => 'Deleted game from recommended game list!',
    'MSG_CONTENT_RECOMMENDATION_ADD_SUCCESS' => 'Added game to recommended game list!',
    'MSG_CONTENT_NOT_SELECT_GAME' => 'No game selected, please select game to continue',
    'MSG_CONTENT_APPROVE_MULTI_GAME' => 'Approved {count} games!',
    'MSG_CONTENT_SUSPEND_MULTI_GAME' => 'Suspend {count} games!',
    'MSG_CONTENT_REJECT_MULTI_GAME' => 'Reject {count} games!',
    'MSG_CONTENT_APPROVE_FALSE_GAME_NOT_PENDING' => 'Approval unsuccessful because game does not pending',
    'MSG_CONTENT_SUSPEND_FALSE_GAME_NOT_PENDING' => 'Suspend unsuccessful because game does not pending',
    'MSG_CONTENT_REJECT_FALSE_GAME_NOT_PENDING' => 'Reject unsuccessful because game does not pending',
    'MSG_CONTENT_APPROVE_SUCCESS' => 'Approval successful',
    'MSG_CONTENT_SUSPEND_SUCCESS' => 'Suspend successful',
    'MSG_CONTENT_REJECT_SUCCESS' => 'Reject successful ',

    'MSG_PRICE_LEVEL_CREATE_SUCCESS' => 'Created pricing!',

    'MSG_ADS_CREATE_SUCCESS' => 'Created banner!',
    'MSG_ADS_UPDATE_SUCCESS' => 'Updated banner!',
    'MSG_ADS_DELETE_SUCCESS' => 'Deleted banner!',
    'MSG_ADS_ACTIVE_SUCCESS' => 'Activated banner!',
    'MSG_ADS_INACTIVE_SUCCESS' => 'Inactivated banner!',
    'MSG_ADS_NOT_SELECT_ADS' => 'No banner selected, please select banner to continue',
    'MSG_ADS_ACTIVE_MULTI_SUCCESS' => 'Activated{ count} banners!',
    'MSG_ADS_INACTIVE_MULTI_SUCCESS' => 'Inactivated {count} banners!',

    'MSG_CONTENT_PACKAGE_CREATE_SUCCESS' => 'Created game package!',
    'MSG_CONTENT_PACKAGE_UPDATE_SUCCESS' => 'Updated game package!',
    'MSG_CONTENT_PACKAGE_DELETE_SUCCESS' => 'Deleted game package!',
    'MSG_CONTENT_PACKAGE_DELETE_can not' => 'Can not delete game package activated',
    'MSG_CONTENT_PACKAGE_ACTIVE_SUCCESS' => 'Activated game package!',
    'MSG_CONTENT_PACKAGE_INACTIVE_SUCCESS' => 'Inactivated game package!',
    'MSG_CONTENT_PACKAGE_ADD_CP_SUCCESS' => 'Added game publishers to package!',
    'MSG_CONTENT_PACKAGE_ADD_CATEGORY_SUCCESS' => 'Added category to package!',
    'MSG_CONTENT_PACKAGE_ADD_GAME_SUCCESS' => 'Added game to package!',
    'MSG_CONTENT_PACKAGE_REMOVE_CP_SUCCESS' => 'Removed game publisher from package!',
    'MSG_CONTENT_PACKAGE_REMOVE_CATEGORY_SUCCESS' => 'Removed category from package!',
    'MSG_CONTENT_PACKAGE_REMOVE_GAME_SUCCESS' => 'Removed game from package!',
    'MSG_CONTENT_PACKAGE_ADD_CP_FALSE_CP_EXIST' => 'Game publisher already existed in the package, please select it again add to the package',
    'MSG_CONTENT_PACKAGE_ADD_CATEGORY_FALSE_CATEGORY_EXIST' => 'The category already existed in the package, please select it again add to the package',
    'MSG_CONTENT_PACKAGE_ADD_GAME_FALSE_GAME_EXIST' => 'Game already existed in the package, please select it again add to the package',
    'MSG_CONTENT_PACKAGE_REMOVE_CP_FALSE_CP_NOT_EXIST' => 'Game publisher does not existed in the package, please select it again remove from the package',
    'MSG_CONTENT_PACKAGE_REMOVE_CATEGORY_FALSE_CATEGORY_NOT_EXIST' => 'The category does not existed existed in the package, please select it again remove from the package',
    'MSG_CONTENT_PACKAGE_REMOVE_GAME_FALSE_GAME_NOT_EXIST' => 'Game does not existed in the package, please select it again remove from the package',

    'MSG_CAMPAIGN_ADS_CREATE_SUCCESS' => 'Created campaign!',
    'MSG_CAMPAIGN_ADS_UPDATE_SUCCESS' => 'Updated campaign!',
    'MSG_CAMPAIGN_ADS_DELETE_SUCCESS' => 'Deleted campaign!',
    'MSG_CAMPAIGN_ADS_DELETE_can not' => 'Can not delete campaign activated',

    'MSG_USER_FEEDBACK_DELETE_SUCCESS' => 'Deleted comment!',

    'MSG_MT_TEMPLATE_CREATE_SUCCESS' => 'Created MT template!',
    'MSG_MT_TEMPLATE_UPDATE_SUCCESS' => 'Updated MT template!',
    'MSG_MT_TEMPLATE_DELETE_SUCCESS' => 'Deleted MT template!',
    'MSG_MT_TEMPLATE_NOT_SELECT_MT_TEMPLATE' => 'No MT template selected, please select MT template to continue',
    'MSG_MT_TEMPLATE_ACTIVE_MULTI_SUCCESS' => 'Activated {count} MT templates',
    'MSG_MT_TEMPLATE_INACTIVE_MULTI_SUCCESS' => 'Inactivated {count} MT templates ',

    /** VALIDATE */
    'VALIDATE_CATEGORY_IMAGE' => 'Information is not valid, category image - limited to 200 KB',
    'VALIDATE_ADS_IMAGE' => 'Information is not valid, banner image - limited to 200 KB',
    'VALIDATE_CAMPAIGN_ADS_NEED_ACOUNT' => 'Before Create media campain, you need to create Ads Agent account',

    'VALIDATE_BE_USER_USERNAME_REQUIED' => 'Information is not valid, username - Minimum 3 characters (including lowercase a-z, 0-9) do not include special characters',
    'VALIDATE_BE_USER_USERNAME_EXIST' => 'Information is not valid, username already existed in the system',
    'VALIDATE_BE_USER_EMAIL_FORMAT' => 'Information is not valid, email format : email@domain.extension',
    'VALIDATE_BE_USER_DESCRIPTION_MAX_LENGTH' => 'Information is not valid, description - must be less than 128 characters',
    'VALIDATE_BE_USER_PHONE_NUMBER_NOT_NULL' => 'Information is not valid, phone number - do not empty',
    'VALIDATE_BE_USER_PHONE_NUMBER_FORMAT' => 'Information is not valid, phone number - Format phone numbers beginning with 0, for example: 0912345678, 012 312 341 234',
    'VALIDATE_BE_USER_PASSWORD_FORMAT' => 'Information is not valid, password has more than 6 characters (including a-z; A-Z, 0-9; special characters: "!@#$%^&*()',
    'VALIDATE_BE_USER_NEW_PASSWORD_FORMAT' => 'Information is not valid, password has more than 6 characters (including a-z; A-Z, 0-9; special characters: "!@#$%^&*()',
    'VALIDATE_BE_USER_CONFIRM_PASSWORD_FORMAT' => 'Information is not valid, password has more than 6 characters (including a-z; A-Z, 0-9; special characters: "!@#$%^&*()',
    'VALIDATE_BE_USER_CONFIRM_PASSWORD_NOT_MATCH' => 'Information is not valid, verify password is incorrect',
    'VALIDATE_BE_USER_OLD_PASSWORD_NOT_NULL' => 'Information is not valid, old password - do not empty',
    'VALIDATE_BE_USER_NEW_PASSWORD_NOT_NULL' => 'Information is not valid, new password - do not empty',

    'VALIDATE_ADS_CONTENT_ID_REQUIRED' => 'Information is not valid, game does not empty',
    'VALIDATE_ADS_NAME_REQUIRED' => 'Information is not valid, advertisement name - limited to 30 characters and do not empty',
    'VALIDATE_ADS_DESCRIPTION_REQUIRED' => 'Information is not valid, description - limited to 256 characters and do not empty',
    'VALIDATE_ADS_IMAGE_REQUIRED' => 'Information is not valid, advertisement image -  do not empty',
    'VALIDATE_ADS_IMAGE_FORMAT' => 'Information is not valid, advertisement image - limited width (100-1000 pixels), length (100-1000 pixels)',

    'VALIDATE_CAMPAIGN_ADS_NAME_FORMAT' => 'Information is not valid, campaign name - Minimum of 4 characters, starting with letters (including a-z, A-Z, 0-9, and special characters _), please re-enter',
    'VALIDATE_CAMPAIGN_ADS_DESCRIPTION_FORMAT' => 'Information is not valid, Description - limited to 256 characters,please enter again',
    'VALIDATE_CAMPAIGN_ADS_ACTIVATED_AT_REQUIRED' => 'Information is not valid, Start date - do not empty, please enter again',
    'VALIDATE_CAMPAIGN_ADS_EXPIRED_AT_REQUIRED' => 'Information is not valid, End date - do not empty, please enter again',

    'VALIDATE_CATEGORY_DISPLAY_NAME_REQUIRED' => 'Information is not valid, category name - limited to 30 characters, not allowed dupplicate the other categories',
    'VALIDATE_CATEGORY_IMAGE_REQUIRED' => 'Information is not valid, category image - limited to 200kB',

    'VALIDATE_CONTENT_NAME_REQUIRED' => 'Information is not valid, Game name - do not empty',
    'VALIDATE_CONTENT_NAME_MAX_LENGTH' => 'Information is not valid, Game name - limited to 64 characters',
    'VALIDATE_CONTENT_DESCRIPTION_MAX_LENGTH' => 'Information is not valid, full description  - limited to 4096 characters',
    'VALIDATE_CONTENT_SHORT_DESCRIPTION_MAX_LENGTH' => 'Information is not valid, Short description - limited to 128 characters',
    'VALIDATE_CONTENT_DISCOUNT_PRICE_COMPARE' => 'Information is not valid, Promotional price need less than price',
    'VALIDATE_CONTENT_CONTACT_EMAIL_FORMAT' => 'Information is not valid, Email format : email@domain.extension',
    'VALIDATE_CONTENT_WEBSITE_FORMAT' => 'Information is not valid, Website URL is not valid',
    'VALIDATE_CONTENT_LIST_CAT_ID_REQUIRED' => 'Information is not valid, need to select category',
    'VALIDATE_CONTENT_ICON_FORMAT' => 'Information is not valid, Logo game - limited to 200kB',


    'VALIDATE_CONTENT_PACKAGE_NAME_REQUIRED' => 'Information is not valid, package name - do not empty',
    'VALIDATE_CONTENT_PACKAGE_NAME_FORMAT' => 'Information is not valid, package name - limited to 60 characters, not allowed dupplicate the other packages',
    'VALIDATE_CONTENT_PACKAGE_DESCRIPTION_REQUIRED' => 'Information is not valid, description - do not empty',
    'VALIDATE_CONTENT_PACKAGE_DESCRIPTION_FORMAT' => 'Information is not valid, description - limited to 256 characters',
    'VALIDATE_CONTENT_PACKAGE_MO_REGISTER_REQUIRED' => 'Information is not valid, Mo Register - do not empty',
    'VALIDATE_CONTENT_PACKAGE_MO_CANCEL_REQUIRED' => 'Information is not valid, Mo Cancel - do not empty',
    'VALIDATE_CONTENT_PACKAGE_PRICE_REQUIRED' => 'Information is not valid, price - do not empty',
    'VALIDATE_CONTENT_PACKAGE_CHARGING_PERIOD_REQUIRED' => 'Information is not valid, renew cycle - do not empty',
    'VALIDATE_CONTENT_PACKAGE_EFFECTIVE_AT_REQUIRED' => 'Information is not valid, Effective Date - do not empty',
    'VALIDATE_CONTENT_PACKAGE_THUMBNAIL_REQUIRED' => 'Information is not valid, package image - do not empty',
    'VALIDATE_CONTENT_PACKAGE_BANNER_REQUIRED' => 'Information is not valid, package banner  - do not empty',
    'VALIDATE_CONTENT_PACKAGE_THUMBNAIL_OVER_HEIGHT' => 'Information is not valid, package image - limited height 512 pixcel',
    'VALIDATE_CONTENT_PACKAGE_THUMBNAIL_OVER_WIDTH' => 'Information is not valid, package image - limited width 512 pixcel',
    'VALIDATE_CONTENT_PACKAGE_BANNER_OVER_HEIGHT' => 'Information is not valid, package banner - limited the highest height 512 pixcel',
    'VALIDATE_CONTENT_PACKAGE_BANNER_OVER_WIDTH' => 'Information is not valid, package banner - maximum width limit 512 pixcel',
    'VALIDATE_CONTENT_PACKAGE_BANNER_UNDER_HEIGHT' => 'Information is not valid, package banner - limited the shortest height 100 pixcel',
    'VALIDATE_CONTENT_PACKAGE_BANNER_UNDER_WIDTH' => 'Information is not valid, package banner - limited the shortest width 100 pixcel',

    'VALIDATE_MT_TEMPLATE_TEMPLATE_NAME_REQUIRED' => 'Information is not valid, MT template name - do not empty',
    'VALIDATE_MT_TEMPLATE_TEMPLATE_NAME_UNIQUE' => 'Information is not valid, MT template name -  already existed in the system',
    'VALIDATE_MT_TEMPLATE_MT_CONTENT_REQUIRED' => 'Information is not valid, MT content - do not empty',

    'VALIDATE_PRICE_LEVEL_UNIQUE' => 'Information is not valid, Price already existed in the system - please try again',

    'VALIDATE_USER_MSISDN' => 'Information is not valid, phone number must be VinaPhone subscribers , format 84|0(91|94|123|124|125|127|129)XXXXXXX',
    'VALIDATE_USER_DESCRIPTION_REQUIRED' => 'Information is not valid, description does not empty',
    'VALIDATE_USER_DESCRIPTION_FORMAT' => 'Information is not valid, description must be less than 128 characters',
    'VALIDATE_USER_USERNAME_REQUIRED' => 'Information is not valid, username - Minimum 3 characters (including lowercase a-z, 0-9) do not include special characters',
    'VALIDATE_USER_USERNAME_UNIQUE' => 'Account already existed in the system',
    'VALIDATE_USER_MSISDN_UNIQUE' => 'Phone number was used to register please check again.',
    'VALIDATE_USER_EMAIL_UNIQUE' => 'Email already registered',
    'VALIDATE_USER_EMAIL_FORMAT' => 'Information is not valid, email format: email@domain.extension',
    'VALIDATE_USER_PASSWORD_FORMAT' => 'Information is not valid, password includes 6-16  letters or numbers, please enter again',
    'VALIDATE_USER_CONFIRM_PASSWORD_REQUIRED' => 'Information is not valid, password - entered password do not match, please enter your password again',





);