<?php
/**
 * Created by PhpStorm.
 * User: TuanPham
 * Date: 11/19/2016
 * Time: 9:09 PM
 */
namespace frontend\widgets;

use common\models\Category;
use common\models\Content;
use common\models\SubscriberFavorite;
use DateTime;
use yii\base\Widget;
use Yii;

class CartBox extends Widget{

    public $message;

    public  function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public  function run()
    {
        if(Yii::$app->user->isGuest){
            $total_favourite = 0;
        }else{
            $total_favourite = SubscriberFavorite::find()
                ->andWhere(['subscriber_id' => Yii::$app->user->id])
                ->count();
        }
        return $this->render('cart-box',[
            'total_favourite' => $total_favourite
        ]);
    }

    public static function getModal(){
        $cb = new CartBox();
        return $cb->render('//shopping-cart/modal-buy-content');
    }
}
