<?php
/**
 * Created by PhpStorm.
 * User: TuanPham
 * Date: 11/19/2016
 * Time: 9:09 PM
 */
namespace frontend\widgets;

use common\models\Category;
use common\models\Content;
use DateTime;
use yii\base\Widget;
use Yii;

class CartBox extends Widget{

    public $message;

    public  function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public  function run()
    {
        $session = Yii::$app->session;
        $cartInfo = $session['cart'];
        $total_price = $totalAmount = 0;
        if(isset($cartInfo)){
            foreach($cartInfo as $key => $value){
                $totalAmount += $value['amount'];
                if($value['price_promotion'] == 0) {
                    $total_price += $value['price'] * $value['amount'];
                }else {
                    $total_price += $value['price_promotion'] * $value['amount'];
                }
            }
        }
        return $this->render('cart-box',[
            'cartInfo'=>$cartInfo,
            'total_price'=>$total_price,
            'totalAmount'=>$totalAmount,
        ]);
    }
}
