<?php
/**
 * Created by PhpStorm.
 * User: TuanPham
 * Date: 11/19/2016
 * Time: 9:09 PM
 */
namespace frontend\widgets;

use common\models\Category;
use yii\base\Widget;
use Yii;

class CategoryLeft extends Widget{

    public $message;

    public  function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public  function run()
    {
        $menu = Category::find()
            ->andWhere(['status' => Category::STATUS_ACTIVE])
            ->andWhere(['parent_id' => null])
            ->all();
        return $this->render('category-left',[
            'menu'=>$menu
        ]);
    }
}
