<?php
/**
 * Created by PhpStorm.
 * User: TuanPham
 * Date: 11/19/2016
 * Time: 9:09 PM
 */
namespace frontend\widgets;

use common\models\Category;
use common\models\Content;
use DateTime;
use yii\base\Widget;
use Yii;

class CateRow extends Widget{

    public $message;

    public  function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public  function run()
    {
    }

    public static function getCateRow($id){
        $cat = Category::findAll(['status'=>Category::STATUS_ACTIVE,'parent_id'=>$id]);
        if(isset($cat)){
            $dt = new CateRow();
            return $dt->render('cate-row',[
                'cat'=>$cat,
            ]);
        }
    }
}
