<?php
/**
 * Created by PhpStorm.
 * User: TuanPham
 * Date: 11/19/2016
 * Time: 9:09 PM
 */
namespace frontend\widgets;

use common\models\Category;
use yii\base\Widget;
use Yii;

class CategoryChildLeft extends Widget{

    public $message;

    public  function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public  function run()
    {

    }

    public static function getCateChildLeft($id){
        $menu = Category::find()
            ->andWhere(['status' => Category::STATUS_ACTIVE])
            ->andWhere(['parent_id' => $id])
            ->all();
        $dy = new CategoryLeft();
        return $dy->render('category-child-left',[
            'menu'=>$menu
        ]);
    }
}
