<?php
/**
 * Created by PhpStorm.
 * User: TuanPham
 * Date: 11/19/2016
 * Time: 9:09 PM
 */

namespace frontend\widgets;

use common\models\Category;
use common\models\Content;
use yii\base\Widget;
use yii\db\Expression;

class ContentContentBody extends Widget
{

    public $message;
    public $id;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $contents = Content::find()
            ->select('content.id,content.code,content.display_name,content.price,content.price_promotion,content.images,content.type')
            ->innerJoin('content_category_asm', 'content_category_asm.content_id = content.id')
            ->andWhere(['content_category_asm.category_id' => $this->id])
            ->andWhere(['content.status' => Content::STATUS_ACTIVE])
            ->andWhere(['content.parent_id' => null])
            ->orderBy(new Expression('rand()'))
            ->limit((7))
            ->all();
        return $this->render('content-content-body', [
            'contents' => $contents,
        ]);
    }

}
