<?php
/**
 * Created by PhpStorm.
 * User: TuanPham
 * Date: 11/19/2016
 * Time: 9:09 PM
 */
namespace frontend\widgets;

use common\models\Category;
use common\models\Content;
use yii\base\Widget;
use Yii;

class ContentBody extends Widget{

    public $message;

    public  function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public  function run()
    {
        $category = Category::find()
            ->andWhere(['status' => Category::STATUS_ACTIVE])
            ->andWhere('parent_id is null')
            ->orderBy(['order_number' => SORT_DESC])
            ->all();
        return $this->render('content-body',[
            'category'=>$category,
        ]);
    }
}
