<?php
/**
 * Created by PhpStorm.
 * User: HungChelsea
 * Date: 25-Mar-17
 * Time: 12:01 PM
 */

namespace frontend\widgets;


use api\models\Category;
use common\models\Content;
use yii\base\Widget;

class FeatureContent extends Widget
{

    public $message;
    public $id;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $category = Category::find()
            ->andWhere(['id' => $this->id])
            ->orFilterWhere(['parent_id' => $this->id])->all();
        $arrCat = [];
        foreach ($category as $item) {
            array_push($arrCat, $item->id);
        }
        $content_feature = Content::find()
            ->innerJoin('content_category_asm', 'content_category_asm.content_id = content.id')
            ->andWhere(['content.status' => Content::STATUS_ACTIVE])
            ->andWhere(['content.is_feature' => Content::IS_FEATURE])
            ->andWhere(['in', 'content_category_asm.category_id', $arrCat])->one();
        return $this->render('feature_content', [
            'content' => $content_feature,
        ]);
    }
}