<?php
/**
 * Created by PhpStorm.
 * User: TuanPham
 * Date: 11/19/2016
 * Time: 9:09 PM
 */
namespace frontend\widgets;

use common\models\Category;
use common\models\Content;
use DateTime;
use yii\base\Widget;
use Yii;

class ForYou extends Widget{

    public $message;

    public  function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public  function run()
    {
        $category = Category::find()
            ->select('id,display_name,images,description')
            ->andWhere(['status'=>Category::STATUS_ACTIVE])
            ->andWhere(['parent_id'=>null])
            ->andWhere(['hide'=>0])
            ->all();
        return $this->render('for-you',[
            'category'=>$category,
        ]);
    }
}
