<?php
/**
 * Created by PhpStorm.
 * User: TuanPham
 * Date: 11/19/2016
 * Time: 9:09 PM
 */
namespace frontend\widgets;

use common\models\Category;
use common\models\Content;
use common\models\ProgramSuppost;
use yii\base\Widget;
use Yii;

class LatestDeals extends Widget{

    public $message;

    public  function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public  function run()
    {
        $contents = Content::find()
            ->select('content.*')
            ->innerJoin('order_detail','order_detail.content_id = content.id')
            ->andWhere(['content.status' => Category::STATUS_ACTIVE])
            ->orderBy(['order_detail.created_at' => SORT_DESC])
            ->limit(5)
            ->all();
        return $this->render('latest-deals',[
            'contents'=>$contents
        ]);
    }
}
