<?php
/**
 * Created by PhpStorm.
 * User: TuanPham
 * Date: 11/19/2016
 * Time: 9:09 PM
 */
namespace frontend\widgets;

use common\models\Category;
use common\models\Content;
use common\models\News;
use DateTime;
use yii\base\Widget;
use Yii;

class ListNews extends Widget{

    public $message;

    public  function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public  function run()
    {
        $news = News::find()
            ->andWhere(['status' => News::STATUS_ACTIVE])
            ->andWhere(['type' => News::STATUS_NEW])
            ->orderBy(['updated_at' => SORT_DESC])
            ->limit(6)
            ->all();
        return $this->render('list-news',[
            'news' => $news
        ]);
    }
}
