<?php
/**
 * Created by PhpStorm.
 * User: TuanPham
 * Date: 11/19/2016
 * Time: 9:09 PM
 */
namespace frontend\widgets;

use common\models\Category;
use yii\base\Widget;
use Yii;
use yii\helpers\Url;

class MenuRight extends Widget{

    public $message;

    public  function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public  function run()
    {
        $menu = Category::find()
            ->andWhere(['status' => Category::STATUS_ACTIVE])
            ->andWhere(['type'=> Category::TYPE_MENU_RIGHT])
            ->all();
        return $this->render('menu-right',[
            'menu'=>$menu
        ]);
    }

    public static function showCategories($categories, $parent_id = 0)
    {
        foreach ($categories as $key => $item)
        {
            /** @var $item Category*/
            // Nếu là chuyên mục con thì hiển thị
            if ($item->parent_id == $parent_id)
            {
                if($item->parent_id == 0){
                    if($item['child_count'] > 0){
                        echo '<li>
                                <a class="parent" href="'.Url::to(['category/index','id'=>$item->id]).'"><img height="30px" class="icon-menu" alt="'.$item->display_name.'" src="'.Category::getImageLinkFE($item->images).'">'.$item->display_name.'</a>';
                    }else{
                        echo '<li><a href="'.Url::to(['category/index','id'=>$item->id]).'"><img height="30px" class="icon-menu" alt="'.$item->display_name.'" src="'.Category::getImageLinkFE($item->images).'">'.$item->display_name.'</a></li>';
                    }
                }
                // Xóa dm đã lặp
                unset($categories[$key]);
                // Chay tim con cap 1 co hinh anh
                MenuRight::getChildLevel1($item['id']);
            }
        }
    }

    public static function getChildLevel1($id){
        $cat1 = Category::find()->andWhere(['status'=>Category::STATUS_ACTIVE])->andWhere(['parent_id' => $id])->all();
        foreach ($cat1 as $item) {
            /** @var $item Category*/
            if($item->location_image == Category::LOCATION_BOTTOM){
                self::getChildLevel1ImageLeft($id);
            }
            if($item->location_image == Category::NO_IMAGE){
                self::getChildlevel1NoImage($id);
            }
        }
    }

    public static function getChildLevel1ImageLeft($id){
        echo '<div class="vertical-dropdown-menu">
                 <div class="vertical-groups col-sm-12">';
        $cat1 = Category::find()->andWhere(['status'=>Category::STATUS_ACTIVE])->andWhere(['parent_id' => $id])->all();
        /** @var  $item Category */
        foreach ($cat1 as $item) {
            echo
                    '<div class="mega-group col-sm-4">
                         <h4 class="mega-group-header"><span>'.$item->display_name.'</span></h4>
                         <ul class="group-link-default">';
            self::getAllChild($item->id);
            echo        '</ul>
                        <a href="'.Url::to(['category/index','id'=>$item->id]).'"><img height="284px" src="'.Category::getImageLinkFE($item->images).'" alt="'.$item->display_name.'"></a>
                     </div>';

        }
        echo        '</div>
              </div>';
    }

    public static function getChildlevel1NoImage($id){
        echo '<ul class="dropdown-menu container-fluid">
                  <li class="block-container">
                      <ul class="block">';
        $cat1 = Category::find()->andWhere(['status'=>Category::STATUS_ACTIVE])->andWhere(['parent_id' => $id])->all();
        /** @var  $item Category */
        foreach ($cat1 as $item) {
            echo '<li class="link_container"><a href="'.Url::to(['category/index','id'=>$item->id]).'">'.$item->display_name.'</a></li>';
        }
        echo '        </ul>
                  </li>
              </ul> ';
    }

    public static function getAllChild($id){
        $categories = Category::findAll(['status'=>Category::STATUS_ACTIVE]);
        foreach ($categories as $key => $item)
        {
            // Nếu là chuyên mục con thì hiển thị
            if ($item->parent_id == $id)
            {
                echo '<li><a href="'.Url::to(['category/index','id'=>$item->id]).'">'.$item->display_name.'</a></li>';
                // Xóa dm đã lặp
                unset($categories[$key]);
                // Chay tim con cap 1 co hinh anh
                MenuRight::getAllChild($item->id);
            }
        }
    }
}
