<?php
/**
 * Created by PhpStorm.
 * User: TuanPham
 * Date: 11/19/2016
 * Time: 9:09 PM
 */
namespace frontend\widgets;

use common\models\Category;
use yii\base\Widget;
use Yii;
use yii\helpers\Url;

class MenuTop extends Widget{

    public $message;

    public  function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public  function run()
    {
        $menu = Category::find()
            ->andWhere(['status' => Category::STATUS_ACTIVE])
            ->andWhere(['type'=> Category::TYPE_MENU_ABOVE])
            ->all();
        return $this->render('menu-top',[
            'menu'=>$menu
        ]);
    }

    public static function showCategories($categories, $parent_id = 0)
    {
        foreach ($categories as $key => $item)
        {
            // Nếu là chuyên mục con thì hiển thị
            if ($item['parent_id'] == $parent_id)
            {
                if($item['parent_id'] == 0){
                    if($item['child_count'] > 0){
                        echo '<li class="dropdown"><a href="'.Url::to(['category/index','id'=>$item['id']]).'" class="dropdown-toggle" data-toggle="dropdown">'.$item['display_name'].'</a>';
                    }else{
                        echo '<li><a href="'.Url::to(['category/index','id'=>$item['id']]).'" class="dropdown-toggle" data-toggle="dropdown">'.$item['display_name'].'</a></li>';
                    }
                }
                // Xóa dm đã lặp
                unset($categories[$key]);
                // Chay tim con cap 1 co hinh anh
                MenuTop::getChildLevel1($item['id']);
            }
        }
    }

    public static function getChildLevel1($id){
        $cat1 = Category::find()->andWhere(['status'=>Category::STATUS_ACTIVE])->andWhere(['parent_id' => $id])->all();
        foreach ($cat1 as $item) {
            /** @var $item Category*/
            if($item->location_image == Category::LOCATION_LEFT){
                self::getChildLevel1ImageLeft($id);
            }
            if($item->location_image == Category::LOCATION_TOP){
                self::getChildLevel1ImageTop($id);
            }
            if($item->location_image == Category::NO_IMAGE){
                self::getChildlevel1NoImage($id);
            }
        }
    }

    public static function getChildLevel1ImageTop($id){
        echo '<ul class="dropdown-menu mega_dropdown" role="menu" style="width: 830px;">';
            $cat1 = Category::find()->andWhere(['status'=>Category::STATUS_ACTIVE])->andWhere(['parent_id' => $id])->all();
            /** @var  $item Category */
        foreach ($cat1 as $item) {
                echo '
                                    <li class="block-container col-sm-3">
                                        <ul class="block">
                                            <li class="img_container">
                                                <a href="'.Url::to(['category/index','id'=>$item->id]).'">
                                                      <img style="height:200px" class="img-responsive" src="' . Category::getImageLinkFE($item->images) . '" alt="' . $item->display_name . '">
                                                </a>
                                            </li>
                                            <li class="link_container group_header">
                                                 <a href="'.Url::to(['category/index','id'=>$item->id]).'">' . $item->display_name . '</a>
                                            </li>';
                                            self::getAllChild($item->id);

                echo                        '</ul>
                                    </li>';
            }
        echo '</ul>';
    }

    public static function getChildLevel1ImageLeft($id){
        echo '<ul class="mega_dropdown dropdown-menu" style="width: 830px;">';
        $cat1 = Category::find()->andWhere(['status'=>Category::STATUS_ACTIVE])->andWhere(['parent_id' => $id])->all();
        /** @var  $item Category */
        foreach ($cat1 as $item) {
            echo
                    '<li class="block-container col-sm-3">
                        <ul class="block">
                            <li class="link_container group_header">
                                <a href="'.Url::to(['category/index','id'=>$item->id]).'">'.$item->display_name.'</a>
                            </li>';
            self::getAllChild($item->id);
            echo            '</ul>
                    </li>
                    <li class="block-container col-sm-3">
                        <ul class="block">
                            <li class="img_container">
                                <img style="height: 200px" src="'.Category::getImageLinkFE($item->images).'" alt="'.$item->display_name.'">
                            </li>
                        </ul>
                    </li>
                    ';

        }
        echo '</ul>';
    }

    public static function getChildlevel1NoImage($id){
        echo '<ul class="dropdown-menu container-fluid">
                  <li class="block-container">
                      <ul class="block">';
        $cat1 = Category::find()->andWhere(['status'=>Category::STATUS_ACTIVE])->andWhere(['parent_id' => $id])->all();
        /** @var  $item Category */
        foreach ($cat1 as $item) {
            echo '<li class="link_container"><a href="'.Url::to(['category/index','id'=>$item->id]).'">'.$item->display_name.'</a></li>';
        }
        echo '        </ul>
                  </li>
              </ul> ';
    }

    public static function getAllChild($id){
        $categories = Category::findAll(['status'=>Category::STATUS_ACTIVE]);
        foreach ($categories as $key => $item)
        {
            // Nếu là chuyên mục con thì hiển thị
            if ($item->parent_id == $id)
            {
                echo '<li class="link_container"><a href="'.Url::to(['category/index','id'=>$item->id]).'">'.$item->display_name.'</a></li>';
                // Xóa dm đã lặp
                unset($categories[$key]);
                // Chay tim con cap 1 co hinh anh
                MenuTop::getAllChild($item->id);
            }
        }
    }
}
