<?php
/**
 * Created by PhpStorm.
 * User: TuanPham
 * Date: 11/19/2016
 * Time: 9:09 PM
 */
namespace frontend\widgets;

use common\models\Category;
use Yii;
use yii\base\Widget;

class MenuContentBody extends Widget
{

    public $message;
    public $id;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $categories = Category::findAll(['parent_id' => $this->id]);
        return $this->render('menu-content-body', [
            'categories' => $categories
        ]);
    }

}
