<?php
/**
 * Created by PhpStorm.
 * User: TuanPham
 * Date: 11/19/2016
 * Time: 9:09 PM
 */
namespace frontend\widgets;

use common\models\Category;
use common\models\Content;
use common\models\InfoPublic;
use DateTime;
use yii\base\Widget;
use Yii;
use yii\web\NotFoundHttpException;

class SearchPriceWidget extends Widget{

    public $message;

    public  function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public  function run()
    {
        $info = InfoPublic::findOne(InfoPublic::ID_DEFAULT);
        if (!$info) {
            throw new NotFoundHttpException(Yii::t('app', 'Not yet setup statics information'));
        }
        return $this->render('search-price',[
            'info' => $info
        ]);
    }
}
