<?php
/**
 * Created by PhpStorm.
 * User: TuanPham
 * Date: 11/19/2016
 * Time: 9:09 PM
 */
namespace frontend\widgets;

use common\models\User;
use yii\base\Widget;
use Yii;

class UserWidget extends Widget{

    public $message;

    public  function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public  function run()
    {
        $id = Yii::$app->user->id;
        $model = User::findOne($id);
        return $this->render('user-widget',[
            'model'=>$model
        ]);
    }
}
