<?php
/**
 * Created by PhpStorm.
 * User: TuanPham
 * Date: 11/19/2016
 * Time: 9:09 PM
 */
namespace frontend\widgets;

use common\models\Category;
use common\models\Content;
use DateTime;
use yii\base\Widget;
use Yii;

class WidgetNewContent extends Widget{

    public $message;
    public $id;

    public  function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public  function run()
    {
        $product_news = Content::find()
            ->select('content.id,content.display_name,content.type,content.short_description,content.price,content.images,content.price_promotion')
            ->andWhere(['content.status'=>Content::STATUS_ACTIVE])
            ->andWhere(['content.type'=>Content::TYPE_NEWEST])
            ->orderBy(['content.created_at'=>'DESC'])
            ->andWhere(['<>', 'content.id', $this->id])
            ->limit(6)
            ->all();
        // sản phẩm sale
        return $this->render('widget-new-content',[
            'product_news'=>$product_news,
        ]);
    }
}
