<?php
/**
 * Created by PhpStorm.
 * User: TuanPham
 * Date: 11/19/2016
 * Time: 9:09 PM
 */
namespace frontend\widgets;

use common\models\Category;
use common\models\Content;
use DateTime;
use yii\base\Widget;
use Yii;

class WidgetNewContent extends Widget{

    public $message;

    public  function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public  function run()
    {
        // tạo khoảng thời gian
        $date = (new DateTime('now'))->setTime(23, 59, 59)->format('Y-m-d H:i:s');
        $date_from = (new DateTime('now'))->modify('-30 days')->setTime(0, 0)->format('Y-m-d H:i:s');
        $now = strtotime($date);
        $from = strtotime($date_from);
        // lấy 6 sản phẩm được tạo trong vòng 1 tháng gần thời điểm hiện tại nhất
        $product_news = Content::find()
            ->select('content.id,content.display_name,content.type,content.short_description,content.price,content.images,content.price_promotion')
            ->innerJoin('content_category_asm','content_category_asm.content_id = content.id')
            ->innerJoin('category','content_category_asm.category_id = category.id')
            ->andWhere('category.is_news <> :is_news',['is_news'=>1])
            ->andWhere(['content.status'=>Content::STATUS_ACTIVE])
            ->andWhere(['content.type'=>Content::TYPE_NEWEST])
            ->andWhere(['>=','content.created_at',$from])
            ->andWhere(['<=','content.created_at',$now])
            ->orderBy(['content.created_at'=>'DESC'])
            ->limit(6)
            ->all();
        // sản phẩm sale
        return $this->render('widget-new-content',[
            'product_news'=>$product_news,
        ]);
    }
}
